function ooeyGUI(workbench)
    f = findobj(gca, 'Tag', workbench.robot.model.name);
	if isempty(f)
		f = findobj(0, 'Tag', workbench.robot.model.name);
		if isempty(f)
			workbench.robot.model.plot(zeros(1, workbench.robot.model.n));
			ax = gca;
		else
			ax = get(c(1), 'Parent');
		end
	else
	ax = gca;
	end
	
	bgcol = [167 178 196]/255;
	handles.fig = get(ax, 'Parent');
	set(ax, 'Outerposition', [0.25 0 0.7 1]);
	handles.curax = ax;
	
	%GUI panel
	panel = uipanel(handles.fig, ...
		'Title', 'ooeyGUI', ...
		'BackgroundColor', bgcol, ...
		'Position', [0.25 0, 0.15, 0.25]);
	set(panel, 'Units', 'pixels');
	handles.panel = panel;
	set(handles.fig, 'Units', 'pixels');
	set(handles.fig, 'ResizeFcn', @(src,event) resize_callback(workbench.robot.model, handles));
	
	%% gui components
	%Exit button and callback
    uicontrol(panel, 'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.80 0.01 0.15 0.15], ...
        'FontUnits', 'normalized', ...
        'FontSize', 0.7, ...
        'CallBack', @(src,event) quit_callback(workbench.robot.model, handles), ...
        'BackgroundColor', 'white', ...
        'ForegroundColor', 'red', ...
        'String', 'X');
	
	%Start toasting button
	handles.startToasting = uicontrol(panel, 'Style', 'pushbutton', ...
		'Units', 'normalized', ...
		'String', 'Start Toasting', ...
		'Position', [0.12 0.05 0.3 0.3]);
	
	%Emergency stop button
	handles.emergencyStop = uicontrol(panel, 'Style', 'pushbutton', ...
		'Units', 'normalized', ...
		'String', '<html>EMERGENCY<br />STOP</html>', ...
		'BackgroundColor', 'red', ...
		'FontSize', 13, ...
		'Position', [0.12 0.4 0.3 0.3]);

	%Darkness of toast slider
	handles.darknessSlider = uicontrol(panel, 'Style', 'slider', ...
		'Units', 'normalized', ...
		'Min', 1, ...
		'Max', 5, ...
		'Value', 3, ...
		'SliderStep', [0.25 0.25], ...
		'Position', [0.12 0.8 0.3 0.1]);
	
	%slider label
	uicontrol(panel, 'Style', 'text', ...
		'Units', 'normalized', ...
		'BackgroundColor', bgcol, ...
		'Position', [0.12 0.9 0.3 0.1], ...
		'String', 'Toast Darkness');
    
	%slider value
	handles.darknessValue = uicontrol(panel, 'Style', 'text', ...
		'Units', 'normalized', ...
		'BackgroundColor', bgcol, ...
		'Position', [0.43 0.79 0.1 0.1], ...
		'String', num2str(3, 1)); 
	
	
	%% Callbacks
	%darkness slider callback
	set(handles.darknessSlider, ...
		'Interruptible', 'off', ...
		'Callback', @(src, event)darkness_callback(src, handles));
	
	set(handles.startToasting, ...
		'Interruptible', 'on', ...
		'Callback', @(src, event)startToasting_callback(src, workbench, handles));
	
	set(handles.emergencyStop, ...
		'Interruptible', 'off', ...
		'Callback', @(src, event)emergencyStop_callback(src, workbench, handles));
	
end

%% Callback Functions
function startToasting_callback(src, workbench, handles)
    darknessValue = get(handles.darknessSlider, 'Value');
    workbench.testAnimate(darknessValue);
end

function emergencyStop_callback(src, workbench, handles)
	workbench.robot.stopState = 1;
end

%callback for darkness slider to change values
function darkness_callback(src, handles)
    newval = get(src, 'Value');
	set(handles.darknessValue, 'String', num2str(newval));
end

%callback to quit gui
function quit_callback(robot, handles)
    set(handles.fig, 'ResizeFcn', '');
    delete(handles.panel);
    set(handles.curax, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1])
end

%callback to resize
function resize_callback(handles)
   fig = gcbo;
   fs = get(fig, 'Position');
   ps = get(handles.panel, 'Position');
   set(handles.curax, 'Units', 'normalized', ...
	   'OuterPosition', [ps(3) 0 fs(3)-ps(3) fs(4)]);
   set(handles.panel, 'Position', [1 fs(4)-ps(4) ps(3:4)]);
end